In [1]:
#Imports
import pandas as pd
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import Dense


/home/prashanth/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [2]:
# Reading the dataset
df = pd.read_csv('./data/housepricedata.csv')

In [3]:
df

LotArea  OverallQual  OverallCond  TotalBsmtSF  FullBath  HalfBath  \
0        8450            7            5          856         2         1   
1        9600            6            8         1262         2         0   
2       11250            7            5          920         2         1   
3        9550            7            5          756         1         0   
4       14260            8            5         1145         2         1   
5       14115            5            5          796         1         1   
6       10084            8            5         1686         2         0   
7       10382            7            6         1107         2         1   
8        6120            7            5          952         2         0   
9        7420            5            6          991         1         0   
10      11200            5            5         1040         1         0   
11      11924            9            5         1175         3         0   
12      12968            5            6          912         1         0   
13      10652            7            5         1494         2         0   
14      10920            6            5         1253         1         1   
15       6120            7            8          832         1         0   
16      11241            6            7         1004         1         0   
17      10791            4            5            0         2         0   
18      13695            5            5         1114         1         1   
19       7560            5            6         1029         1         0   
20      14215            8            5         1158         3         1   
21       7449            7            7          637         1         0   
22       9742            8            5         1777         2         0   
23       4224            5            7         1040         1         0   
24       8246            5            8         1060         1         0   
25      14230            8            5         1566         2         0   
26       7200            5            7          900         1         0   
27      11478            8            5         1704         2         0   
28      16321            5            6         1484         1         0   
29       6324            4            6          520         1         0   
...       ...          ...          ...          ...       ...       ...   
1430    21930            5            5          732         2         1   
1431     4928            6            6          958         2         0   
1432    10800            4            6          656         2         0   
1433    10261            6            5          936         2         1   
1434    17400            5            5         1126         2         0   
1435     8400            6            9         1319         1         1   
1436     9000            4            6          864         1         0   
1437    12444            8            5         1932         2         0   
1438     7407            6            7          912         1         0   
1439    11584            7            6          539         2         1   
1440    11526            6            7          588         2         0   
1441     4426            6            5          848         1         0   
1442    11003           10            5         1017         2         1   
1443     8854            6            6          952         1         0   
1444     8500            7            5         1422         2         0   
1445     8400            6            5          814         1         0   
1446    26142            5            7         1188         1         0   
1447    10000            8            5         1220         2         1   
1448    11767            4            7          560         1         1   
1449     1533            5            7          630         1         0   
1450     9000            5            5          896  

In [4]:
# Converting the dataframe into an array.
dataset = df.values

In [5]:
dataset

array([[ 8450,     7,     5, ...,     0,   548,     1],
       [ 9600,     6,     8, ...,     1,   460,     1],
       [11250,     7,     5, ...,     1,   608,     1],
       ...,
       [ 9042,     7,     9, ...,     2,   252,     1],
       [ 9717,     5,     6, ...,     0,   240,     0],
       [ 9937,     5,     6, ...,     0,   276,     0]])

In [6]:
# Extracting X 
X = dataset[:,0:10]

In [25]:
# Y dataset
Y = dataset[:,10]
Y

array([1, 1, 1, ..., 1, 0, 0])

In [8]:
min_max_scaler = preprocessing.MinMaxScaler()
X_scale = min_max_scaler.fit_transform(X)

/home/prashanth/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


In [9]:
# Array after scaling
X_scale

array([[0.0334198 , 0.66666667, 0.5       , ..., 0.5       , 0.        ,
        0.3864598 ],
       [0.03879502, 0.55555556, 0.875     , ..., 0.33333333, 0.33333333,
        0.32440056],
       [0.04650728, 0.66666667, 0.5       , ..., 0.33333333, 0.33333333,
        0.42877292],
       ...,
       [0.03618687, 0.66666667, 1.        , ..., 0.58333333, 0.66666667,
        0.17771509],
       [0.03934189, 0.44444444, 0.625     , ..., 0.25      , 0.        ,
        0.16925247],
       [0.04037019, 0.44444444, 0.625     , ..., 0.33333333, 0.        ,
        0.19464034]])

In [10]:
# Using sklearn test_train_split to split data into test and train dataset
X_train, X_val_and_test, Y_train, Y_val_and_test = train_test_split(X_scale, Y, test_size=0.3)

In [11]:
# Usinf train_test_split to create validation data
X_val, X_test, Y_val, Y_test = train_test_split(X_val_and_test, Y_val_and_test, test_size=0.5)

In [12]:
# Printing the shape of all the variables
print(X_train.shape, X_val.shape, X_test.shape, Y_train.shape, Y_val.shape, Y_test.shape)

(1022, 10) (219, 10) (219, 10) (1022,) (219,) (219,)


In [24]:
print(Y_train)

[0 0 0 ... 0 1 1]


In [13]:
# Define the architecture of the model
model = Sequential([    Dense(32, activation='relu', input_shape=(10,)),    Dense(32, activation='relu'),    Dense(1, activation='sigmoid'),])


In [14]:
# Compiling the model
model.compile(optimizer='sgd',loss='binary_crossentropy', metrics=['accuracy'])


In [15]:
# Training your model
hist = model.fit(X_train, Y_train,batch_size=32, epochs=100,validation_data=(X_val, Y_val))

Train on 1022 samples, validate on 219 samples
Epoch 1/100
1022/1022 [==============================] - 1s 534us/step - loss: 0.6763 - acc: 0.5215 - val_loss: 0.6689 - val_acc: 0.5479
Epoch 2/100
1022/1022 [==============================] - 0s 55us/step - loss: 0.6701 - acc: 0.5479 - val_loss: 0.6630 - val_acc: 0.5662
Epoch 3/100
1022/1022 [==============================] - 0s 55us/step - loss: 0.6649 - acc: 0.5988 - val_loss: 0.6575 - val_acc: 0.6393
Epoch 4/100
1022/1022 [==============================] - 0s 72us/step - loss: 0.6597 - acc: 0.6791 - val_loss: 0.6515 - val_acc: 0.7489
Epoch 5/100
1022/1022 [==============================] - 0s 73us/step - loss: 0.6539 - acc: 0.7192 - val_loss: 0.6449 - val_acc: 0.7900
Epoch 6/100
1022/1022 [==============================] - 0s 67us/step - loss: 0.6477 - acc: 0.7622 - val_loss: 0.6382 - val_acc: 0.8311
Epoch 7/100
1022/1022 [==============================] - 0s 73us/step - loss: 0.6413 - acc: 0.7681 - val_loss: 0.6311 - val_acc: 0.8539


1022/1022 [==============================] - 0s 51us/step - loss: 0.3105 - acc: 0.8826 - val_loss: 0.2958 - val_acc: 0.8767
Epoch 61/100
1022/1022 [==============================] - 0s 57us/step - loss: 0.3086 - acc: 0.8875 - val_loss: 0.2951 - val_acc: 0.8767
Epoch 62/100
1022/1022 [==============================] - 0s 52us/step - loss: 0.3064 - acc: 0.8845 - val_loss: 0.2969 - val_acc: 0.8858
Epoch 63/100
1022/1022 [==============================] - 0s 48us/step - loss: 0.3046 - acc: 0.8894 - val_loss: 0.2923 - val_acc: 0.8767
Epoch 64/100
1022/1022 [==============================] - 0s 47us/step - loss: 0.3031 - acc: 0.8865 - val_loss: 0.2938 - val_acc: 0.8813
Epoch 65/100
1022/1022 [==============================] - 0s 46us/step - loss: 0.3018 - acc: 0.8924 - val_loss: 0.2934 - val_acc: 0.8813
Epoch 66/100
1022/1022 [==============================] - 0s 48us/step - loss: 0.3001 - acc: 0.8885 - val_loss: 0.2907 - val_acc: 0.8767
Epoch 67/100
1022/1022 [==============================

In [16]:
# Evaluate the model
model.evaluate(X_test,Y_test)[1]

219/219 [==============================] - 0s 77us/step


0.8675799113974724